# Generated by Django 2.2.3 on 2020-05-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': '图书举报', 'verbose_name_plural': '图书举报'},
        ),
    ]
