# Generated by Django 2.2.3 on 2020-05-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200529_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(default='举报标题', max_length=50, verbose_name='举报标题'),
        ),
    ]
