# Generated by Django 2.2.3 on 2020-05-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(default='This guy is too lazy to leave anything here!', max_length=128, verbose_name='签名'),
        ),
    ]
