# Generated by Django 2.2.3 on 2020-05-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_moviecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '书评', 'verbose_name_plural': '书评'},
        ),
        migrations.AlterModelOptions(
            name='moviecomment',
            options={'verbose_name': '影评', 'verbose_name_plural': '影评'},
        ),
        migrations.RenameField(
            model_name='moviecomment',
            old_name='post',
            new_name='movie',
        ),
    ]
