# Generated by Django 2.2.3 on 2020-05-25 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_moviecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviecomment',
            old_name='created_time',
            new_name='moviecreated_time',
        ),
        migrations.RenameField(
            model_name='moviecomment',
            old_name='name',
            new_name='moviename',
        ),
        migrations.RenameField(
            model_name='moviecomment',
            old_name='post',
            new_name='moviepost',
        ),
        migrations.RenameField(
            model_name='moviecomment',
            old_name='text',
            new_name='movietext',
        ),
    ]
