# Generated by Django 2.2.3 on 2020-05-25 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20200525_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieComment',
        ),
    ]
