# Generated by Django 2.2.3 on 2020-05-25 05:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200523_1102'),
        ('comments', '0007_delete_moviecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50, verbose_name='名字')),
                ('movie_text', models.TextField(verbose_name='内容')),
                ('movie_created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('movie_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.MoviePost', verbose_name='文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
