# Generated by Django 2.2.3 on 2020-05-25 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_moviecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieComment',
        ),
    ]
