# Generated by Django 2.2.3 on 2020-05-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_delete_moviecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '书评', 'verbose_name_plural': '书评'},
        ),
    ]
