# Generated by Django 2.2.3 on 2020-05-26 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_auto_20200525_1705'),
        ('comments', '0004_auto_20200524_2229'),
    ]

    operations = [
    ]
