<<<<<<< Updated upstream
# Generated by Django 2.2.3 on 2020-05-25 23:18
=======
# Generated by Django 2.2.3 on 2020-06-01 12:23
>>>>>>> Stashed changes

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< Updated upstream
        ('forum', '0003_topicpost'),
=======
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.CreateModel(
            name='TopicDiscuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('text', models.TextField(verbose_name='内容')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '话题讨论',
                'verbose_name_plural': '话题讨论',
            },
        ),
    ]
