# Generated by Django 2.2.3 on 2020-06-01 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        ('TopicDiscuss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicdiscuss',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.TopicPost', verbose_name='话题'),
        ),
    ]
