# Generated by Django 2.2.3 on 2020-06-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopicDiscuss', '0002_topicdiscuss_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicdiscuss',
            name='title',
            field=models.CharField(default='title', max_length=70, verbose_name='标题'),
        ),
    ]
