# Generated by Django 2.2.3 on 2020-05-30 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': '书籍', 'verbose_name_plural': '书籍'},
        ),
    ]
