# Generated by Django 2.2.3 on 2020-06-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='im',
            field=models.BooleanField(default=False),
        ),
    ]
