# Generated by Django 2.2.3 on 2020-06-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200601_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
