# Generated by Django 2.2.3 on 2020-05-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200529_1708'),
        ('forum', '0002_auto_20200530_1151'),
    ]

    operations = [
    ]
