# Generated by Django 2.2.3 on 2020-05-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200523_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepost',
            name='title',
            field=models.CharField(max_length=70, verbose_name='影视'),
        ),
    ]
