# Generated by Django 2.2.3 on 2020-05-30 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200529_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppost',
            options={'default_permissions': (), 'ordering': ['-created_time'], 'permissions': (('grouppost_delete', '讨论删除权限'),), 'verbose_name': '小组讨论', 'verbose_name_plural': '小组讨论'},
        ),
    ]
