# Generated by Django 2.2.3 on 2020-05-31 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_merge_20200530_1638'),
        ('forum', '0003_auto_20200530_0232'),
    ]

    operations = [
    ]
