# Generated by Django 2.2.3 on 2020-06-01 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_merge_20200531_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='top_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='置顶时间'),
        ),
    ]
