# Generated by Django 2.2.3 on 2020-06-04 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20200601_1016'),
        ('forum', '0005_auto_20200603_1609'),
    ]

    operations = [
    ]
