<<<<<<< HEAD
# Generated by Django 2.2.3 on 2020-05-26 10:14
=======
<<<<<<< Updated upstream
# Generated by Django 2.2.3 on 2020-05-25 05:46
=======
# Generated by Django 2.2.3 on 2020-06-01 12:23
>>>>>>> Stashed changes
>>>>>>> jh

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('forum', '0001_initial'),
=======
<<<<<<< Updated upstream
        ('forum', '0002_auto_20200523_1102'),
=======
>>>>>>> Stashed changes
>>>>>>> jh
    ]

    operations = [
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('text', models.TextField(verbose_name='内容')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
<<<<<<< HEAD
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.MoviePost', verbose_name='文章')),
            ],
            options={
                'verbose_name': '影评',
                'verbose_name_plural': '影评',
            },
        ),
=======
<<<<<<< Updated upstream
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Post', verbose_name='文章')),
=======
                ('like_num', models.IntegerField(default=0)),
                ('dislike_num', models.IntegerField(default=0)),
>>>>>>> Stashed changes
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='MovieDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='MovieLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_comments.MovieComment')),
            ],
        ),
>>>>>>> jh
    ]
