# Generated by Django 2.2.3 on 2020-05-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviecomment',
            options={'verbose_name': '影评', 'verbose_name_plural': '影评'},
        ),
        migrations.AlterField(
            model_name='moviecomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.MoviePost', verbose_name='文章'),
        ),
    ]
